- hosts: sixsq:!consul_servers
  sudo: yes
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: Install the package "nginx"
    apt:
      name: nginx
      state: present
  - service:
      name: nginx
      state: started
  - name: Run the command 
    tags:
      - always
    shell: >
      /bin/echo "From SixSq: $(date)" >> /var/www/html/index.nginx-debian.html 
  - name: register nginx with an http check
    consul:
      service_name: nginx
      service_port: 80
      token: "{{ agent_token }}"
      interval: 60s
      http: http://localhost:80
