- hosts: localhost
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: Install the package "nginx"
    apt:
      name: nginx
      state: present
  - service:
      name: nginx
      state: started
