---
- name: Pull Mode!
  hosts: localhost
 
  tasks:
 
  - name: Pull Mode!
    shell: echo "Pull mode triggered"

- name: Include a play after another play
  import_playbook: pull-mode/helloworld-pull.yaml
  
- name: Include the reverse tunneling playbook
  import_playbook: pull-mode/reverse-tunnel.yaml
