---
- hosts: localhost
  tasks:
  - name: Pull Ubuntu image latest
    docker_image:
      name: ubuntu
  - name: Container management
    docker_container:
      name: mycontainer
      image: ubuntu
      command: sleep 5000

