---
- hosts: localhost
  tasks:
  - name: Pull Ubuntu image latest
    docker_image:
      name: ubuntu
      source: pull
  - name: Container management
    docker_container:
      name: mycontainerAdrien
      image: ubuntu
      command: sleep 5000

