---
- name: Nuvla Update
  hosts: managers

  tasks:
  - name: Install pip
    apt:
      name: python-pip

  - pip:
      name:
        - jsondiff
        - pyyaml

  - name: update Nuvla stack
    docker_stack:
      name: demo
      state: present
      prune: yes
      compose:
        - /tmp/deployment/demo/docker-compose.yml

