---
- name: Nuvla Update
  hosts: managers

  tasks:
  - pip:
      name:
        - jsondiff
        - pyyaml

  - name: update Nuvla stack
    docker_stack:
      name: demo
      state: present
      compose:
        - /tmp/deployment/demo/docker-compose.yml

