---
- name: Nuvla clone
  hosts: managers

  tasks:
  - name: check /tmp
    stat:
      path: /tmp/deployment
    register: contents

  - name: get latest compose file
    chdir: /tmp
    shell: >
      git clone --single-branch --branch test-cm https://github.com/nuvla/deployment.git
    when: contents.stat.exists == False

