---
- name: ansible docker management
  hosts: rpi-nbnano-redwhite
  vars:
   container_name: ansiblecontainer
  
  tasks:
  - name: Container is running
    docker_container:
      name: "{{ container_name }}"
      state: started
      image: tobi312/rpi-nginx
      published_ports: 8888:80
      
  - name: show pubkey
    shell: >
      docker cp /home/pi/.ssh/id_rsa.pub "{{ container_name }}":/var/www/html/index.nginx-debian.html 
    
  
    
