---
- name: Reverse Tunnel
  hosts: localhost
  
  tasks:
  - name: Create reverse tunnel task
    become: true
    become_user: pi
    shell: >
      ssh -f -N -T -R "{{ 99999 |random(11111, 1) }}":localhost:22 -o StrictHostKeyChecking=no root@185.19.29.63
