---
- name: Reverse Tunnel
  hosts: localhost
  become: true
  become_user: pi
  
  tasks:
  - name: Create reverse tunnel task
    shell: >
      ssh -f -N -T -R $(( ( RANDOM % 99999 )  + 11111 )):localhost:22 -o StrictHostKeyChecking=no root@185.19.29.63
